export type AssessmentSummary = {
    traitSummary: string;
    keyTraits: string[];
    interestSummary: string;
    riasecScores: { [type: string]: number };
    intelligenceSummary: string;
    aptitudeScores: {
      patternRecognition: number;
      logicalReasoning: number;
      numericalReasoning: number;
      criticalReasoning: number;
      patternRecognitionPct: number;
      logicalReasoningPct: number;
      numericalReasoningPct: number;
      criticalReasoningPct: number;
      totalScore: number;
      totalPct: number;
    };
    familyContext: string;
    strengths: string[];
    improvements: string[];
  };
  
  export type CareerRecommendation = {
    jobTitle: string;
    industry: string;
    jobDuties: string;
    keySkills: string;
    salary: string;
    education: string;
    careerPath: string;
    cities: string;
    workEnvironment: string;
    whyFit: string;
    alternatives: string;
  };
  
  export type CareerReport = {
    studentName: string;
    tier: "Free" | "Paid";
    date: string;
    introduction: string;
    interpretationGuide: string;
    summary: AssessmentSummary;
    recommendations: CareerRecommendation[];
    nextSteps: string[];
    disclaimer: string;
  };
  
  // Pure function: generate a holistic report from provided data
  export function generateCareerReport({
    user,
    assessments,
    recommendations,
  }: {
    user: any;
    assessments: Record<string, any>;
    recommendations: CareerRecommendation[];
  }): CareerReport {
    const studentName = user.firstName ? `${user.firstName} ${user.lastName || ""}`.trim() : "User";
    const tier = user.tier || "Free";
    const hexaco = assessments.hexaco;
    const riasec = assessments.riasec;
    const mi = assessments.mi;
    const family = assessments.family;
    const aptitude = assessments.aptitude;
    const date = new Date().toISOString().split('T')[0];
    const summary: AssessmentSummary = {
      traitSummary: hexaco?.traitScores ? JSON.stringify(hexaco.traitScores) : "",
      keyTraits: [],
      interestSummary: riasec?.categoryScores ? JSON.stringify(riasec.categoryScores) : "",
      riasecScores: riasec?.categoryScores || {},
      intelligenceSummary: mi?.miScores ? JSON.stringify(mi.miScores) : "",
      aptitudeScores: aptitude?.categories || {},
      familyContext: family?.summary || "",
      strengths: [],
      improvements: [],
    };
    const introduction =
      "Welcome to your personalized career assessment report! This report summarizes your unique strengths, interests, and potential career paths based on your responses.";
    const interpretationGuide =
      "This report interprets your assessment results across four areas: personality, interests, cognitive abilities, and family context. Use this to reflect on your journey and inform your future choices.";
    const nextSteps =
      tier === "Paid"
        ? [
            "Explore the recommended career paths and research each one in more detail.",
            "Reach out to professionals or alumni in your fields of interest.",
            "Plan to develop skills in your areas for improvement.",
            "Set up a session with a qualified career counsellor for more personalized guidance.",
          ]
        : [
            "Read about the suggested careers and think about what interests you.",
            "Discuss these options with your teachers, parents, or a counsellor.",
          ];
    const disclaimer =
      "These recommendations are generated by AI and based on your responses. Many factors influence success and satisfaction in any career, including personal motivation, real-world experience, and changing opportunities. Please consider discussing your report with a qualified career counsellor or mentor before making important decisions.";
    return {
      studentName,
      tier,
      date,
      introduction,
      interpretationGuide,
      summary,
      recommendations,
      nextSteps,
      disclaimer,
    };
  }